
package visual;

import controle.PersonalController;
import controle.SessionController;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Frame;
import java.awt.TextField;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;
import modelo.Personal;
import utils.PersonalLogado;

/**
 *
 * @author Vitória Moreira de Souza
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form inicial
     */
    public TelaInicial() {
        initComponents();
        panel_cadastrar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_papel_parede = new javax.swing.JPanel();
        panel_all = new javax.swing.JPanel();
        panel_img = new javax.swing.JPanel();
        txt_titulo = new javax.swing.JLabel();
        img_login = new javax.swing.JLabel();
        img_peso_preto = new javax.swing.JLabel();
        panel_control = new javax.swing.JPanel();
        panel_entrar = new javax.swing.JPanel();
        input_senha_login = new java.awt.TextField();
        input_email_login = new java.awt.TextField();
        btn_entrar = new java.awt.Button();
        chk_lembrar = new java.awt.Checkbox();
        link_esqueci_senha = new javax.swing.JLabel();
        panel_cadastrar = new javax.swing.JPanel();
        input_nome_cadastrar = new java.awt.TextField();
        input_endereco_cadastrar = new java.awt.TextField();
        btn_cadastrar = new java.awt.Button();
        input_cr_cadastrar = new java.awt.TextField();
        input_senha_cadastrar = new java.awt.TextField();
        input_email_cadastrar = new java.awt.TextField();
        select_profissao_cadastrar = new java.awt.Choice();
        input_confirmar_senha_cadastrar = new java.awt.TextField();
        input_data_nasc_cadastrar = new javax.swing.JFormattedTextField();
        input_telefone_cadastrar = new javax.swing.JFormattedTextField();
        panel_links = new javax.swing.JPanel();
        link_entrar = new javax.swing.JLabel();
        txt_divisor = new javax.swing.JLabel();
        link_cadastrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE ACADÊMIAS BODY BUILDER (TELA INICIAL)");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setState(Frame.MAXIMIZED_BOTH);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        panel_papel_parede.setBackground(new java.awt.Color(246, 246, 246));
        panel_papel_parede.setLayout(new java.awt.GridBagLayout());

        panel_all.setBackground(new java.awt.Color(255, 250, 250));
        panel_all.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.lightGray));

        panel_img.setBackground(new java.awt.Color(68, 68, 68));

        txt_titulo.setFont(new java.awt.Font("Courier 10 Pitch", 0, 36)); // NOI18N
        txt_titulo.setForeground(new java.awt.Color(254, 254, 254));
        txt_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_titulo.setText("Body Builder");

        img_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imgs/img_login.png"))); // NOI18N

        javax.swing.GroupLayout panel_imgLayout = new javax.swing.GroupLayout(panel_img);
        panel_img.setLayout(panel_imgLayout);
        panel_imgLayout.setHorizontalGroup(
            panel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imgLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_imgLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(img_login, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_imgLayout.setVerticalGroup(
            panel_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imgLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txt_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img_login, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        img_peso_preto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imgs/img_peso_preto.png"))); // NOI18N

        panel_control.setBackground(new java.awt.Color(254, 254, 254));
        panel_control.setLayout(new java.awt.CardLayout());

        panel_entrar.setBackground(new java.awt.Color(254, 254, 254));
        panel_entrar.setBorder(null);
        panel_entrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        input_senha_login.setBackground(new java.awt.Color(254, 254, 254));
        input_senha_login.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        input_senha_login.setForeground(new java.awt.Color(1, 1, 1));
        input_senha_login.setText("Digite aqui sua senha");
        input_senha_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_senha_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_senha_loginFocusLost(evt);
            }
        });

        input_email_login.setBackground(new java.awt.Color(254, 254, 254));
        input_email_login.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        input_email_login.setForeground(new java.awt.Color(1, 1, 1));
        input_email_login.setText("Digite aqui seu email");
        input_email_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_email_loginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_email_loginFocusLost(evt);
            }
        });

        btn_entrar.setBackground(new java.awt.Color(76, 76, 76));
        btn_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_entrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        btn_entrar.setForeground(new java.awt.Color(254, 254, 254));
        btn_entrar.setLabel("Entrar");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });

        chk_lembrar.setBackground(new java.awt.Color(254, 254, 254));
        chk_lembrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chk_lembrar.setLabel("Lembrar-me");

        link_esqueci_senha.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        link_esqueci_senha.setForeground(new java.awt.Color(1, 1, 1));
        link_esqueci_senha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        link_esqueci_senha.setText("<html><u>Esqueceu sua senha?</u></html>");
        link_esqueci_senha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panel_entrarLayout = new javax.swing.GroupLayout(panel_entrar);
        panel_entrar.setLayout(panel_entrarLayout);
        panel_entrarLayout.setHorizontalGroup(
            panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_entrarLayout.createSequentialGroup()
                .addGroup(panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_entrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_email_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_senha_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_entrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_entrarLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(link_esqueci_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 97, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panel_entrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chk_lembrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_entrarLayout.setVerticalGroup(
            panel_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_entrarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(input_email_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(input_senha_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(chk_lembrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(link_esqueci_senha)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        panel_control.add(panel_entrar, "panel_entrar");

        panel_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        panel_cadastrar.setBorder(null);

        input_nome_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_nome_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        input_nome_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_nome_cadastrar.setText("Digite aqui seu nome completo");
        input_nome_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_nome_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_nome_cadastrarFocusLost(evt);
            }
        });

        input_endereco_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_endereco_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        input_endereco_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_endereco_cadastrar.setText("Digite aqui seu endereço");
        input_endereco_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_endereco_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_endereco_cadastrarFocusLost(evt);
            }
        });

        btn_cadastrar.setBackground(new java.awt.Color(76, 76, 76));
        btn_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(254, 254, 254));
        btn_cadastrar.setLabel("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        input_cr_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_cr_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        input_cr_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_cr_cadastrar.setText("CR(N ou EF)");
        input_cr_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_cr_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_cr_cadastrarFocusLost(evt);
            }
        });

        input_senha_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_senha_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        input_senha_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_senha_cadastrar.setText("Digite aqui sua senha");
        input_senha_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_senha_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_senha_cadastrarFocusLost(evt);
            }
        });

        input_email_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_email_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        input_email_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_email_cadastrar.setText("Digite aqui seu email");
        input_email_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_email_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_email_cadastrarFocusLost(evt);
            }
        });

        select_profissao_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        select_profissao_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        select_profissao_cadastrar.add("Nutricionista");
        select_profissao_cadastrar.add("Personal");

        input_confirmar_senha_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_confirmar_senha_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        input_confirmar_senha_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_confirmar_senha_cadastrar.setText("Confirme aqui sua senha");
        input_confirmar_senha_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_confirmar_senha_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_confirmar_senha_cadastrarFocusLost(evt);
            }
        });

        input_data_nasc_cadastrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            input_data_nasc_cadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_data_nasc_cadastrar.setText("  00/00/0000    ");
        input_data_nasc_cadastrar.setToolTipText("Digite aqui sua data de nescimento");
        input_data_nasc_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        input_data_nasc_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_data_nasc_cadastrarFocusGained(evt);
            }
        });

        input_telefone_cadastrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        try {
            input_telefone_cadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_telefone_cadastrar.setText("(00) 00000-0000    ");
        input_telefone_cadastrar.setToolTipText("Digite aqui seu telefone");
        input_telefone_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        input_telefone_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_telefone_cadastrarFocusGained(evt);
            }
        });

        javax.swing.GroupLayout panel_cadastrarLayout = new javax.swing.GroupLayout(panel_cadastrar);
        panel_cadastrar.setLayout(panel_cadastrarLayout);
        panel_cadastrarLayout.setHorizontalGroup(
            panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cadastrarLayout.createSequentialGroup()
                .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cadastrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(select_profissao_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_telefone_cadastrar))
                        .addGap(25, 25, 25)
                        .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_data_nasc_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_cr_cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_cadastrarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_email_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_senha_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_confirmar_senha_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_cadastrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(input_endereco_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_cadastrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(input_nome_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_cadastrarLayout.setVerticalGroup(
            panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cadastrarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(input_nome_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(input_endereco_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_telefone_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_data_nasc_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(select_profissao_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_cr_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(input_email_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(input_senha_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(input_confirmar_senha_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_control.add(panel_cadastrar, "panel_cadastrar");

        panel_links.setBackground(new java.awt.Color(254, 254, 254));

        link_entrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        link_entrar.setForeground(java.awt.Color.lightGray);
        link_entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        link_entrar.setText("<html><u>ENTRAR</u></html>");
        link_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_entrarMouseClicked(evt);
            }
        });

        txt_divisor.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        txt_divisor.setForeground(new java.awt.Color(1, 1, 1));
        txt_divisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_divisor.setText("|");

        link_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        link_cadastrar.setForeground(java.awt.Color.black);
        link_cadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        link_cadastrar.setText("CADASTRAR");
        link_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_cadastrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_linksLayout = new javax.swing.GroupLayout(panel_links);
        panel_links.setLayout(panel_linksLayout);
        panel_linksLayout.setHorizontalGroup(
            panel_linksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_linksLayout.createSequentialGroup()
                .addComponent(link_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_divisor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(link_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_linksLayout.setVerticalGroup(
            panel_linksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(link_entrar)
            .addComponent(txt_divisor)
            .addComponent(link_cadastrar)
        );

        javax.swing.GroupLayout panel_allLayout = new javax.swing.GroupLayout(panel_all);
        panel_all.setLayout(panel_allLayout);
        panel_allLayout.setHorizontalGroup(
            panel_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_allLayout.createSequentialGroup()
                .addComponent(panel_img, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_allLayout.createSequentialGroup()
                        .addGroup(panel_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_allLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panel_control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_allLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(panel_links, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_allLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img_peso_preto)
                        .addGap(133, 133, 133))))
        );
        panel_allLayout.setVerticalGroup(
            panel_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_allLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(img_peso_preto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_links, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panel_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_papel_parede.add(panel_all, new java.awt.GridBagConstraints());

        getContentPane().add(panel_papel_parede);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_telefone_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_telefone_cadastrarFocusGained
        mudarTexto(input_telefone_cadastrar, "(00) 00000-0000", "");
    }//GEN-LAST:event_input_telefone_cadastrarFocusGained

    private void input_data_nasc_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_data_nasc_cadastrarFocusGained
        mudarTexto(input_telefone_cadastrar, "00/00/0000", "  /  /    ");
    }//GEN-LAST:event_input_data_nasc_cadastrarFocusGained

    private void input_confirmar_senha_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_confirmar_senha_cadastrarFocusLost
        mudarTextoSenha(input_confirmar_senha_cadastrar, "", "Confirme aqui sua senha");
    }//GEN-LAST:event_input_confirmar_senha_cadastrarFocusLost

    private void input_confirmar_senha_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_confirmar_senha_cadastrarFocusGained
        input_confirmar_senha_cadastrar.setEchoChar('*');
        mudarTexto(input_confirmar_senha_cadastrar, "Confirme aqui sua senha", "");
    }//GEN-LAST:event_input_confirmar_senha_cadastrarFocusGained

    private void input_email_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_email_cadastrarFocusLost
        mudarTexto(input_email_cadastrar, "", "Confirme aqui seu email");
    }//GEN-LAST:event_input_email_cadastrarFocusLost

    private void input_email_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_email_cadastrarFocusGained
        mudarTexto(input_email_cadastrar, "Digite aqui seu email", "");
    }//GEN-LAST:event_input_email_cadastrarFocusGained

    private void input_senha_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_senha_cadastrarFocusLost
        mudarTextoSenha(input_senha_cadastrar, "", "Digite aqui sua senha");
    }//GEN-LAST:event_input_senha_cadastrarFocusLost

    private void input_senha_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_senha_cadastrarFocusGained
        input_senha_cadastrar.setEchoChar('*');
        mudarTexto(input_senha_cadastrar, "Digite aqui sua senha", "");
    }//GEN-LAST:event_input_senha_cadastrarFocusGained

    private void input_cr_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cr_cadastrarFocusLost
        mudarTexto(input_cr_cadastrar, "", "CR(N ou EF)");
    }//GEN-LAST:event_input_cr_cadastrarFocusLost

    private void input_cr_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cr_cadastrarFocusGained
        mudarTexto(input_cr_cadastrar, "CR(N ou EF)", "");
    }//GEN-LAST:event_input_cr_cadastrarFocusGained

    private void input_endereco_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_endereco_cadastrarFocusLost
        mudarTexto(input_endereco_cadastrar, "", "Digite aqui seu endereço");
    }//GEN-LAST:event_input_endereco_cadastrarFocusLost

    private void input_endereco_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_endereco_cadastrarFocusGained
        mudarTexto(input_endereco_cadastrar, "Digite aqui seu endereço", "");
    }//GEN-LAST:event_input_endereco_cadastrarFocusGained

    private void input_nome_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nome_cadastrarFocusLost
        mudarTexto(input_nome_cadastrar, "", "Digite aqui seu nome completo");
    }//GEN-LAST:event_input_nome_cadastrarFocusLost

    private void input_nome_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nome_cadastrarFocusGained
        mudarTexto(input_nome_cadastrar, "Digite aqui seu nome completo", "");
    }//GEN-LAST:event_input_nome_cadastrarFocusGained

    private void input_email_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_email_loginFocusLost
        mudarTexto(input_email_login, "","Digite aqui seu email");
    }//GEN-LAST:event_input_email_loginFocusLost

    private void input_email_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_email_loginFocusGained
        mudarTexto(input_email_login, "Digite aqui seu email", "");
    }//GEN-LAST:event_input_email_loginFocusGained

    private void input_senha_loginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_senha_loginFocusLost
        mudarTextoSenha(input_senha_login, "", "Digite aqui sua senha");
    }//GEN-LAST:event_input_senha_loginFocusLost

    private void input_senha_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_senha_loginFocusGained
        input_senha_login.setEchoChar('*');
        mudarTexto(input_senha_login, "Digite aqui sua senha", "");
    }//GEN-LAST:event_input_senha_loginFocusGained

    private void link_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_cadastrarMouseClicked
        ((CardLayout) panel_control.getLayout()).show(panel_control, "panel_cadastrar");
        panel_control.revalidate();

        link_cadastrar.setForeground(Color.lightGray);
        link_cadastrar.setText("<html><u>CADASTRAR</u></html>");
        
        link_entrar.setForeground(Color.black);
        link_entrar.setText("ENTRAR");
    }//GEN-LAST:event_link_cadastrarMouseClicked

    private void link_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_entrarMouseClicked
        ((CardLayout) panel_control.getLayout()).show(panel_control, "panel_entrar");
        panel_control.revalidate();
        
        link_entrar.setForeground(Color.lightGray);
        link_entrar.setText("<html><u>ENTRAR</u></html>");
        
        link_cadastrar.setForeground(Color.black);
        link_cadastrar.setText("CADASTRAR");
    }//GEN-LAST:event_link_entrarMouseClicked

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        String email = input_email_login.getText();
        String senha = input_senha_login.getText();
        
        try {
            SessionController.login(email, senha);

            if(PersonalLogado.getInstance().getToken().isEmpty()){
                System.out.println("Erro");
            }else{
                TelaPersonal a = new TelaPersonal();
                a.setVisible(true);
                this.dispose();
            }
            
        } catch (Exception ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        String nome = input_nome_cadastrar.getText();
        String endereco = input_endereco_cadastrar.getText();
        
        String telefone = input_telefone_cadastrar.getText();
        String data = input_data_nasc_cadastrar.getText();
        
       // String profissao = input_profissao_cadastrar.getText();
        String cr = input_cr_cadastrar.getText();
        
        String email = input_email_cadastrar.getText();

        String senha = input_senha_cadastrar.getText();
        String confirmar_senha = input_confirmar_senha_cadastrar.getText();
        
        
        try {
            Personal personal = PersonalController.cadastro(nome, email, senha, confirmar_senha, data, telefone, cr, endereco);
            
            if(personal.getId().isEmpty()){
                System.out.println("Erro");
            }else{
                System.out.println("Cadastrado");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
        
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_cadastrar;
    private java.awt.Button btn_entrar;
    private java.awt.Checkbox chk_lembrar;
    private javax.swing.JLabel img_login;
    private javax.swing.JLabel img_peso_preto;
    private java.awt.TextField input_confirmar_senha_cadastrar;
    private java.awt.TextField input_cr_cadastrar;
    private javax.swing.JFormattedTextField input_data_nasc_cadastrar;
    private java.awt.TextField input_email_cadastrar;
    private java.awt.TextField input_email_login;
    private java.awt.TextField input_endereco_cadastrar;
    private java.awt.TextField input_nome_cadastrar;
    private java.awt.TextField input_senha_cadastrar;
    private java.awt.TextField input_senha_login;
    private javax.swing.JFormattedTextField input_telefone_cadastrar;
    private javax.swing.JLabel link_cadastrar;
    private javax.swing.JLabel link_entrar;
    private javax.swing.JLabel link_esqueci_senha;
    private javax.swing.JPanel panel_all;
    private javax.swing.JPanel panel_cadastrar;
    private javax.swing.JPanel panel_control;
    private javax.swing.JPanel panel_entrar;
    private javax.swing.JPanel panel_img;
    private javax.swing.JPanel panel_links;
    private javax.swing.JPanel panel_papel_parede;
    private java.awt.Choice select_profissao_cadastrar;
    private javax.swing.JLabel txt_divisor;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
    
    private void mudarTexto(TextField input, String txt_antigo, String txt_novo){
        if(input.getText().equalsIgnoreCase(txt_antigo)){
            input.setText(txt_novo);
        }
    }
    
    private void mudarTexto(JTextField input, String txt_antigo, String txt_novo){
        if(input.getText().equalsIgnoreCase(txt_antigo)){
            input.setText(txt_novo);
        }
    }
    
    private void mudarTextoSenha(TextField input, String txt_antigo, String txt_novo){
        if(input.getText().equalsIgnoreCase(txt_antigo)){
            input.setText(txt_novo);
            input.setEchoChar('\u0000');
        }
    }
}
