/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Access;

import command.Invocador;
import control.AlunoController;
import control.ExercicioController;
import control.SessionController;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import view.Insert.InserExercicio;
import view.Insert.IsertAluno;

/**
 *
 * @author vivi
 */
public final class AccessMainPersonal extends javax.swing.JFrame {


    private static AccessMainPersonal tela_personal;
    
    private AccessMainPersonal() {
        initComponents();
        iniciar();
    }
    
    public static AccessMainPersonal getInstance(){
        if(tela_personal == null){
            tela_personal = new AccessMainPersonal();
        }
        return tela_personal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        personal = new javax.swing.JPanel();
        panel_navegacao = new javax.swing.JPanel();
        link_inicio = new javax.swing.JLabel();
        link_exercicios = new javax.swing.JLabel();
        link_alunos = new javax.swing.JLabel();
        link_suporte = new javax.swing.JLabel();
        link_sair = new javax.swing.JLabel();
        txt_navegacao = new javax.swing.JLabel();
        txt_nome_usuario = new javax.swing.JLabel();
        table_principal = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        input_pesquisar = new java.awt.TextField();
        btn_pesquisar = new java.awt.Button();
        btn_cadastrar = new java.awt.Button();
        btn_atualizar_tabela = new java.awt.Button();
        txt_titulo_tela = new javax.swing.JLabel();
        panel_control = new javax.swing.JPanel();
        panel_main = new javax.swing.JPanel();
        txt_aniversariantes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_exercicio = new javax.swing.JPanel();
        panel_main2 = new javax.swing.JPanel();
        txt_exercicio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_alunos = new javax.swing.JPanel();
        panel_main1 = new javax.swing.JPanel();
        txt_alunos_ativos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_excluir = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);

        main.setMaximumSize(new java.awt.Dimension(700, 400));
        main.setMinimumSize(new java.awt.Dimension(700, 400));
        main.setPreferredSize(new java.awt.Dimension(700, 400));
        main.setLayout(new java.awt.CardLayout());

        personal.setBackground(new java.awt.Color(254, 254, 254));
        personal.setMaximumSize(new java.awt.Dimension(700, 400));
        personal.setMinimumSize(new java.awt.Dimension(700, 400));
        personal.setPreferredSize(new java.awt.Dimension(700, 400));

        panel_navegacao.setBackground(new java.awt.Color(68, 68, 68));
        panel_navegacao.setMaximumSize(new java.awt.Dimension(230, 370));
        panel_navegacao.setMinimumSize(new java.awt.Dimension(230, 370));
        panel_navegacao.setName(""); // NOI18N
        panel_navegacao.setPreferredSize(new java.awt.Dimension(230, 370));

        link_inicio.setBackground(new java.awt.Color(218, 214, 210));
        link_inicio.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        link_inicio.setForeground(new java.awt.Color(218, 214, 210));
        link_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/img_inicio.png"))); // NOI18N
        link_inicio.setText(" Inicio");
        link_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link_inicio.setName("link_inicio"); // NOI18N
        link_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_inicioMouseClicked(evt);
            }
        });

        link_exercicios.setBackground(new java.awt.Color(218, 214, 210));
        link_exercicios.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        link_exercicios.setForeground(new java.awt.Color(254, 254, 254));
        link_exercicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/img_lista.png"))); // NOI18N
        link_exercicios.setText(" Lista de Exercicio");
        link_exercicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link_exercicios.setName("link_exercicios"); // NOI18N
        link_exercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_exerciciosMouseClicked(evt);
            }
        });

        link_alunos.setBackground(new java.awt.Color(218, 214, 210));
        link_alunos.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        link_alunos.setForeground(new java.awt.Color(254, 254, 254));
        link_alunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/img_alunos.png"))); // NOI18N
        link_alunos.setText(" Alunos");
        link_alunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link_alunos.setName("link_alunos"); // NOI18N
        link_alunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_alunosMouseClicked(evt);
            }
        });

        link_suporte.setBackground(new java.awt.Color(218, 214, 210));
        link_suporte.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        link_suporte.setForeground(new java.awt.Color(254, 254, 254));
        link_suporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/img_suporte.png"))); // NOI18N
        link_suporte.setText(" Suporte");
        link_suporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link_suporte.setName("link_suporte"); // NOI18N
        link_suporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_suporteMouseClicked(evt);
            }
        });

        link_sair.setBackground(new java.awt.Color(218, 214, 210));
        link_sair.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        link_sair.setForeground(new java.awt.Color(254, 254, 254));
        link_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/img_sair.png"))); // NOI18N
        link_sair.setText(" Sair");
        link_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link_sair.setName("link_sair"); // NOI18N
        link_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                link_sairMouseClicked(evt);
            }
        });

        txt_navegacao.setBackground(new java.awt.Color(218, 214, 210));
        txt_navegacao.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        txt_navegacao.setForeground(new java.awt.Color(220, 220, 220));
        txt_navegacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_navegacao.setText("Navegação Principal");
        txt_navegacao.setName("txt_navegacao"); // NOI18N

        txt_nome_usuario.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        txt_nome_usuario.setForeground(new java.awt.Color(254, 254, 254));
        txt_nome_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nome_usuario.setText("Nome usuario");
        txt_nome_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_nome_usuario.setName("txt_nome_usuario"); // NOI18N
        txt_nome_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nome_usuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_navegacaoLayout = new javax.swing.GroupLayout(panel_navegacao);
        panel_navegacao.setLayout(panel_navegacaoLayout);
        panel_navegacaoLayout.setHorizontalGroup(
            panel_navegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(link_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(link_alunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(link_exercicios, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
            .addComponent(link_suporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_navegacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_nome_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(link_sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_navegacaoLayout.setVerticalGroup(
            panel_navegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navegacaoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txt_nome_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_navegacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(link_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(link_exercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(link_alunos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(link_suporte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(link_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        tabela.setBackground(new java.awt.Color(254, 254, 254));
        tabela.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        tabela.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        tabela.setForeground(new java.awt.Color(1, 1, 1));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setRowHeight(20);
        tabela.setShowGrid(true);
        tabela.setShowVerticalLines(false);
        table_principal.setViewportView(tabela);
        tabela.getAccessibleContext().setAccessibleName("");

        input_pesquisar.setBackground(new java.awt.Color(254, 254, 254));
        input_pesquisar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_pesquisar.setForeground(new java.awt.Color(1, 1, 1));
        input_pesquisar.setText("Pesquise aqui...");
        input_pesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_pesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_pesquisarFocusLost(evt);
            }
        });

        btn_pesquisar.setBackground(new java.awt.Color(68, 68, 68));
        btn_pesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_pesquisar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_pesquisar.setForeground(new java.awt.Color(254, 254, 254));
        btn_pesquisar.setLabel("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        btn_cadastrar.setBackground(new java.awt.Color(68, 68, 68));
        btn_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(254, 254, 254));
        btn_cadastrar.setLabel("+");

        btn_atualizar_tabela.setBackground(new java.awt.Color(68, 68, 68));
        btn_atualizar_tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_atualizar_tabela.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_atualizar_tabela.setForeground(new java.awt.Color(254, 254, 254));
        btn_atualizar_tabela.setLabel("Atualizar Tabela");

        txt_titulo_tela.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        txt_titulo_tela.setForeground(new java.awt.Color(1, 1, 1));
        txt_titulo_tela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_titulo_tela.setText("Inicio");

        panel_control.setBackground(new java.awt.Color(25, 0, 255));
        panel_control.setBorder(null);
        panel_control.setMaximumSize(new java.awt.Dimension(215, 80));
        panel_control.setMinimumSize(new java.awt.Dimension(215, 80));
        panel_control.setLayout(new java.awt.CardLayout());

        panel_main.setBackground(new java.awt.Color(254, 254, 254));
        panel_main.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panel_main.setMaximumSize(new java.awt.Dimension(215, 80));
        panel_main.setMinimumSize(new java.awt.Dimension(215, 80));
        panel_main.setPreferredSize(new java.awt.Dimension(215, 80));

        txt_aniversariantes.setBackground(new java.awt.Color(218, 214, 210));
        txt_aniversariantes.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        txt_aniversariantes.setForeground(new java.awt.Color(1, 1, 1));
        txt_aniversariantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_aniversariantes.setText("X aniversatiantes");
        txt_aniversariantes.setName("txt_navegacao"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/img_bolo.png"))); // NOI18N

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_main.setLayout(panel_mainLayout);
        panel_mainLayout.setHorizontalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_aniversariantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_mainLayout.setVerticalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_aniversariantes)
                .addGap(8, 8, 8))
        );

        panel_control.add(panel_main, "panel_inicio");

        panel_exercicio.setMaximumSize(new java.awt.Dimension(215, 80));
        panel_exercicio.setMinimumSize(new java.awt.Dimension(215, 80));
        panel_exercicio.setPreferredSize(new java.awt.Dimension(215, 80));

        panel_main2.setBackground(new java.awt.Color(254, 254, 254));
        panel_main2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panel_main2.setMaximumSize(new java.awt.Dimension(215, 80));
        panel_main2.setMinimumSize(new java.awt.Dimension(215, 80));

        txt_exercicio.setBackground(new java.awt.Color(218, 214, 210));
        txt_exercicio.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        txt_exercicio.setForeground(new java.awt.Color(1, 1, 1));
        txt_exercicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_exercicio.setText("X sao meus");
        txt_exercicio.setName("txt_navegacao"); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/img_biblioteca.png"))); // NOI18N

        javax.swing.GroupLayout panel_main2Layout = new javax.swing.GroupLayout(panel_main2);
        panel_main2.setLayout(panel_main2Layout);
        panel_main2Layout.setHorizontalGroup(
            panel_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_exercicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_main2Layout.setVerticalGroup(
            panel_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_main2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_exercicio)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout panel_exercicioLayout = new javax.swing.GroupLayout(panel_exercicio);
        panel_exercicio.setLayout(panel_exercicioLayout);
        panel_exercicioLayout.setHorizontalGroup(
            panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
            .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_exercicioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_main2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_exercicioLayout.setVerticalGroup(
            panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_exercicioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_main2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_control.add(panel_exercicio, "panel_exercicio");

        panel_alunos.setMaximumSize(new java.awt.Dimension(215, 80));
        panel_alunos.setMinimumSize(new java.awt.Dimension(215, 80));
        panel_alunos.setPreferredSize(new java.awt.Dimension(215, 80));

        panel_main1.setBackground(new java.awt.Color(254, 254, 254));
        panel_main1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panel_main1.setMaximumSize(new java.awt.Dimension(215, 80));
        panel_main1.setMinimumSize(new java.awt.Dimension(215, 80));

        txt_alunos_ativos.setBackground(new java.awt.Color(218, 214, 210));
        txt_alunos_ativos.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        txt_alunos_ativos.setForeground(new java.awt.Color(1, 1, 1));
        txt_alunos_ativos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_alunos_ativos.setText("X alunos ativos");
        txt_alunos_ativos.setName("txt_navegacao"); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/img_alunos.png"))); // NOI18N

        javax.swing.GroupLayout panel_main1Layout = new javax.swing.GroupLayout(panel_main1);
        panel_main1.setLayout(panel_main1Layout);
        panel_main1Layout.setHorizontalGroup(
            panel_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_alunos_ativos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_main1Layout.setVerticalGroup(
            panel_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_main1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_alunos_ativos)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout panel_alunosLayout = new javax.swing.GroupLayout(panel_alunos);
        panel_alunos.setLayout(panel_alunosLayout);
        panel_alunosLayout.setHorizontalGroup(
            panel_alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
            .addGroup(panel_alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_alunosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_main1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_alunosLayout.setVerticalGroup(
            panel_alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(panel_alunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_alunosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_main1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel_control.add(panel_alunos, "panel_alunos");

        btn_excluir.setActionCommand("-");
        btn_excluir.setBackground(new java.awt.Color(68, 68, 68));
        btn_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_excluir.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(254, 254, 254));
        btn_excluir.setLabel("-");

        javax.swing.GroupLayout personalLayout = new javax.swing.GroupLayout(personal);
        personal.setLayout(personalLayout);
        personalLayout.setHorizontalGroup(
            personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalLayout.createSequentialGroup()
                .addComponent(panel_navegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_titulo_tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(table_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalLayout.createSequentialGroup()
                        .addComponent(input_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(personalLayout.createSequentialGroup()
                                .addComponent(btn_atualizar_tabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalLayout.createSequentialGroup()
                                .addComponent(btn_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(personalLayout.createSequentialGroup()
                    .addGap(242, 242, 242)
                    .addComponent(panel_control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(243, Short.MAX_VALUE)))
        );
        personalLayout.setVerticalGroup(
            personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txt_titulo_tela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_atualizar_tabela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(input_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addComponent(panel_navegacao, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(personalLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(panel_control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(251, Short.MAX_VALUE)))
        );

        main.add(personal, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void link_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_inicioMouseClicked
        String [] campos_tabela = {"id_verdadeiro", "id", "nome"};
        mudarTela("link_inicio", "Inicio dos Treinos", "panel_inicio", campos_tabela, AlunoController.listaAlunosUsuarioSemStatus(), atualizar_inicio, cadastrar_inicio, excluir_aluno);
    }//GEN-LAST:event_link_inicioMouseClicked
    
    private void link_exerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_exerciciosMouseClicked
        String [] campos_tabela = {"id_verdadeiro", "id", "nome", "grupo", "autor"};
        mudarTela("link_exercicios", "Lista de Exercicios", "panel_exercicio", campos_tabela, ExercicioController.listaExercicios(), atualizar_exercicio, cadastrar_exercicio, excluir_exercicio);
    }//GEN-LAST:event_link_exerciciosMouseClicked

    private void link_alunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_alunosMouseClicked
        String [] campos_tabela = {"id_verdadeiro", "id", "nome", "status"};
        mudarTela("link_alunos", "Alunos", "panel_alunos", campos_tabela, AlunoController.listaAlunosUsuario(), atualizar_exercicio, cadastrar_aluno, excluir_aluno);
    }//GEN-LAST:event_link_alunosMouseClicked

    private void link_suporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_suporteMouseClicked
        AccessSuporte.getInstance().setVisible(true);
    }//GEN-LAST:event_link_suporteMouseClicked

    private void link_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_link_sairMouseClicked
        Object[] options = { "Nao", "Sim" };
        int n = JOptionPane.showOptionDialog(this, "Deseja mesmo sair?", "Mensagem do sistema", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,  null, options, options[1]);
        if(n == 1){
            SessionController.setLogout();
            System.exit(0);
        }
    }//GEN-LAST:event_link_sairMouseClicked

    // Invocador do padrão command na pasta "command"
    Invocador command = Invocador.getInstace();
    
    private void input_pesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_pesquisarFocusGained
        input_pesquisar.setText(command.executaComando(Invocador.Apagado, "Pesquise aqui...", input_pesquisar.getText()));
    }//GEN-LAST:event_input_pesquisarFocusGained

    private void input_pesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_pesquisarFocusLost
        input_pesquisar.setText(command.desfaz(input_pesquisar.getText()));
    }//GEN-LAST:event_input_pesquisarFocusLost

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
       pesquisarUsuario(input_pesquisar.getText());
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void txt_nome_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nome_usuarioMouseClicked
        AcessConta.getInstance().setVisible(true);
    }//GEN-LAST:event_txt_nome_usuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccessMainPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccessMainPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccessMainPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccessMainPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccessMainPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_atualizar_tabela;
    private java.awt.Button btn_cadastrar;
    private java.awt.Button btn_excluir;
    private java.awt.Button btn_pesquisar;
    private java.awt.TextField input_pesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel link_alunos;
    private javax.swing.JLabel link_exercicios;
    private javax.swing.JLabel link_inicio;
    private javax.swing.JLabel link_sair;
    private javax.swing.JLabel link_suporte;
    private javax.swing.JPanel main;
    private javax.swing.JPanel panel_alunos;
    private javax.swing.JPanel panel_control;
    private javax.swing.JPanel panel_exercicio;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_main1;
    private javax.swing.JPanel panel_main2;
    private javax.swing.JPanel panel_navegacao;
    private javax.swing.JPanel personal;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane table_principal;
    private javax.swing.JLabel txt_alunos_ativos;
    private javax.swing.JLabel txt_aniversariantes;
    private javax.swing.JLabel txt_exercicio;
    private javax.swing.JLabel txt_navegacao;
    private javax.swing.JLabel txt_nome_usuario;
    private javax.swing.JLabel txt_titulo_tela;
    // End of variables declaration//GEN-END:variables
    
      // Procura os alunos dentro da lista
    private void pesquisarUsuario(String pesquisa){
        DefaultTableModel model_info = (DefaultTableModel)tabela.getModel();
        String linha_conteudo = "";
        for(int i = 0; i < model_info.getRowCount(); i++){
            for(int j = 1; j < model_info.getColumnCount(); j++){
                linha_conteudo +=  model_info.getValueAt(i, j);
            }
            
            if(!linha_conteudo.contains(pesquisa)){
                model_info.removeRow(i);
                i--;
            }
            
            linha_conteudo = "";
        }
    }
    private void preencherTabela(ArrayList<String> dados, String [] campos_colunas){
         // Constroi um parâmetro de tabela que começa com 0 linha, 0 coluna
        DefaultTableModel tbm = (DefaultTableModel) tabela.getModel();

        //Enquanto a linha for maior que 0, ela será excluida
        while (tbm.getRowCount() > 0) {
            tbm.removeRow(0);
        }
        
        mudarTabelaColunas(campos_colunas);
        //Repetido que se repetirá até Estoque a for todo repetido
        if (dados != null) {
            for (int i = 0; i < dados.size(); i++) {
                //Adiciona a linha de acordo com o contador
                tbm.addRow(new String[i]);
                String[] campo_separado = dados.get(i).split("/");
                
                for(int j = 0; j <= campo_separado.length; j++){
                    if(j == 1){
                        tabela.setValueAt((i+1), i, j);
                    }else if(j >= 2){
                        tabela.setValueAt(campo_separado[j-1], i, j);
                    }else{
                        tabela.setValueAt(campo_separado[j], i, j);
                    }
                }
            }
        }
    }
    private void mudarFonte(String link){
        Component[] components = panel_navegacao.getComponents();
        for (int i=0; i < components.length; i++) {
            Color comp = new Color (220,220,220);
            if(!components[i].getName().equalsIgnoreCase("txt_navegacao")){
                comp = (components[i].getName().equalsIgnoreCase(link))? new Color (152,152,152) : new Color (254,254,254);
            }
            components[i].setForeground(comp);
        }
    }
    private void switchPanel(String panel){
        ((CardLayout) panel_control.getLayout()).show(panel_control, panel);
        panel_control.revalidate();
    }
    private void mudarTabelaColunas(String campos[]){
        //JTable variable name is jTable1_info....
        DefaultTableModel model_info = (DefaultTableModel)tabela.getModel();
        model_info.setColumnCount(campos.length);
       
        tabela.getColumnModel().getColumn(0).setMaxWidth(0);
        tabela.getColumnModel().getColumn(0).setMinWidth(0);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabela.getColumnModel().getColumn(0).setResizable(false);
        
        tabela.getColumnModel().getColumn(1).setMaxWidth(100);
        tabela.getColumnModel().getColumn(1).setMinWidth(100);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(100);
        
        for(int i = 0; i < campos.length; i++){
            TableColumn coluna = tabela.getColumnModel().getColumn(i);
            coluna.setModelIndex(i);
            coluna.setHeaderValue(campos[i]);
        }
        tabela.repaint();
    }
        
    private void setNomeUsuario(){
        String nome =  SessionController.getNomeUsuario();
        if(nome != null){
            txt_nome_usuario.setText(nome);
        }else{
            txt_nome_usuario.setText("null");
        }
    }
    private void setNumAniversariantes(){
        int count = AlunoController.numAniversariantes();
        txt_aniversariantes.setText(count+" aniversariantes");
    }
    private void setNumAlunosAtivos(){
        int alunosAtivos = AlunoController.numAlunosAtivos();
        txt_alunos_ativos.setText(alunosAtivos+ " alunos ativos");
    }
    private void setNumMeusExercicios(){
        int exercicios = ExercicioController.numExerciciosUsuario();
        txt_exercicio.setText(exercicios+ " exercicios sao meus");
    }

    private void mudarTela(String link, String titulo, String panel, String [] campos_tabela, ArrayList<String> valores_tabela, MouseAdapter atualizar, MouseAdapter cadastrar, MouseAdapter tabela_click){
        mudarFonte(link);
        txt_titulo_tela.setText(titulo);
        switchPanel(panel);
        
        preencherTabela(valores_tabela, campos_tabela);
        
        MouseListener[] a = btn_atualizar_tabela.getMouseListeners();

        for(int i = 0; i < a.length; i++){
            btn_atualizar_tabela.removeMouseListener(a[i]);
        }
        
        btn_atualizar_tabela.addMouseListener(atualizar);
        
        a = btn_cadastrar.getMouseListeners();

        for(int i = 0; i < a.length; i++){
            btn_cadastrar.removeMouseListener(a[i]);
        }
        
        btn_cadastrar.addMouseListener(cadastrar);
        
        a = btn_excluir.getMouseListeners();
        for(int i = 0; i < a.length; i++){
            btn_excluir.removeMouseListener(a[i]);
        }
        
        btn_excluir.addMouseListener(tabela_click);
    }

    
    MouseAdapter atualizar_inicio = new MouseAdapter() { 
        public void mouseClicked(MouseEvent me) { 
            String [] campos_tabela = {"id_verdadeiro", "id", "nome"};
            preencherTabela(AlunoController.listaAlunosUsuarioSemStatus(), campos_tabela);
        } 
    };
    MouseAdapter atualizar_exercicio = new MouseAdapter() { 
        public void mouseClicked(MouseEvent me) { 
            String [] campos_tabela = {"id_verdadeiro", "id", "nome", "grupo", "autor"};
            preencherTabela(ExercicioController.listaExercicios(), campos_tabela);
        } 
    };
    MouseAdapter atualizar_aluno = new MouseAdapter() { 
        public void mouseClicked(MouseEvent me) { 
            String [] campos_tabela = {"id_verdadeiro", "id", "nome", "status"};
            preencherTabela(AlunoController.listaAlunosUsuario(), campos_tabela);
        } 
    };
    
    
    MouseAdapter cadastrar_inicio = new MouseAdapter() { 
        public void mouseClicked(MouseEvent me) { 
            int linha = tabela.getSelectedRow();
            if(linha >= 0) {
                AccessAlunoTreino.getInstance(tabela.getValueAt(linha, 0).toString()).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(AccessMainPersonal.getInstance(),"SELECIONE UM ALUNO", "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }
        } 
    };
    MouseAdapter cadastrar_exercicio = new MouseAdapter() { 
        public void mouseClicked(MouseEvent me) { 
            InserExercicio.getInstance().setVisible(true);
        } 
    };
    MouseAdapter cadastrar_aluno = new MouseAdapter() { 
        public void mouseClicked(MouseEvent me) { 
            IsertAluno.getInstance().setVisible(true);
        } 
    };
   
    
    MouseAdapter excluir_exercicio = new MouseAdapter() { 
        public void mouseClicked(MouseEvent me) { 
            int linha = tabela.getSelectedRow();
                               
            if(linha >= 0) {
                String id = tabela.getValueAt(linha, 0).toString();
                String autor = tabela.getValueAt(linha, 4).toString();
                if(autor.equalsIgnoreCase("system")){
                    JOptionPane.showMessageDialog(AccessMainPersonal.getInstance(),"IMPOSSIVEL DELETAR EXERCICIO DO SISTEMA", "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
                }else{
                    Object[] options = { "Nao", "Sim" };
                    int n = JOptionPane.showOptionDialog(null, "Deseja mesmo apagar linha selecionada?", "Mensagem do sistema", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE,  null, options, options[1]);
                    if(n == 1){
                        if(ExercicioController.deletarExercicio(id)){
                            JOptionPane.showMessageDialog(AccessMainPersonal.getInstance(),"LINHA DELETADA DO SISTEMA", "Mensagem do sistema", JOptionPane.PLAIN_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(AccessMainPersonal.getInstance(),"ERRO AO DELETAR", "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                
            }                   
        }
    };
    MouseAdapter excluir_aluno = new MouseAdapter() { 
        public void mouseClicked(MouseEvent me) { 
            int linha = tabela.getSelectedRow();
            if(linha >= 0) {
                JOptionPane.showMessageDialog(AccessMainPersonal.getInstance(),"APENAS ALUNOS PODEM DELETAR SUAS CONTAS", "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
            }                   
        }
    };
    
     MouseAdapter tabela_aluno = new MouseAdapter() { 
        public void mouseClicked(MouseEvent me) { 
            int linha = tabela.getSelectedRow();
            if(linha >= 0) {
                
            }                   
        }
    };
    
    private void iniciar(){
        setNomeUsuario();
        setNumAniversariantes();
        setNumAlunosAtivos();
        setNumMeusExercicios();

        String [] campos_tabela = {"id_verdadeiro", "id", "nome"};
        mudarTela("link_inicio", "Inicio dos Treinos", "panel_inicio", campos_tabela, AlunoController.listaAlunosUsuarioSemStatus(), atualizar_inicio, cadastrar_inicio, excluir_aluno);
    }
     
}
