/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Access;

import command.Invocador;
import control.PersonalController;
import javax.swing.JOptionPane;
import utils.PersonalLogado;

/**
 *
 * @author vivi
 */
public class AcessConta extends javax.swing.JFrame {

    // Invocador do padrão command na pasta "command"
    Invocador command = Invocador.getInstace();
    private static AcessConta acessar;
    /**
     * Creates new form AcessConta
     */
    private AcessConta() {
        initComponents();
         preencherInformacoes();
    }
    
    public static AcessConta getInstance(){
        if(acessar == null){
            acessar = new AcessConta();
        }
        return acessar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cadastrar = new javax.swing.JPanel();
        txt_title1 = new javax.swing.JLabel();
        btn_cadastrar_cadastrar = new java.awt.Button();
        input_nome_cadastrar = new java.awt.TextField();
        input_endereco_cadastrar = new java.awt.TextField();
        input_telefone_cadastrar = new javax.swing.JFormattedTextField();
        input_data_nasc_cadastrar = new javax.swing.JFormattedTextField();
        select_profissao_cadastrar = new java.awt.Choice();
        input_cr_cadastrar = new java.awt.TextField();
        input_email_cadastrar = new java.awt.TextField();
        input_senha_cadastrar = new java.awt.TextField();
        input_confirmar_senha_cadastrar = new java.awt.TextField();
        input_senha_antiga_cadastrar = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(662, 420));
        setMinimumSize(new java.awt.Dimension(662, 420));

        panel_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        panel_cadastrar.setMaximumSize(new java.awt.Dimension(662, 420));
        panel_cadastrar.setMinimumSize(new java.awt.Dimension(662, 420));
        panel_cadastrar.setName("panel_cadastrar"); // NOI18N
        panel_cadastrar.setPreferredSize(new java.awt.Dimension(662, 420));

        txt_title1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        txt_title1.setForeground(new java.awt.Color(1, 1, 1));
        txt_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_title1.setText("Sua Conta");

        btn_cadastrar_cadastrar.setBackground(new java.awt.Color(76, 76, 76));
        btn_cadastrar_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cadastrar_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_cadastrar_cadastrar.setForeground(new java.awt.Color(254, 254, 254));
        btn_cadastrar_cadastrar.setLabel("Atualizar Conta");
        btn_cadastrar_cadastrar.setMaximumSize(new java.awt.Dimension(136, 25));
        btn_cadastrar_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_cadastrarActionPerformed(evt);
            }
        });

        input_nome_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_nome_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_nome_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_nome_cadastrar.setText("Digite aqui seu nome completo");
        input_nome_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_nome_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_nome_cadastrarFocusLost(evt);
            }
        });

        input_endereco_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_endereco_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_endereco_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_endereco_cadastrar.setText("Digite aqui seu endereço");
        input_endereco_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_endereco_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_endereco_cadastrarFocusLost(evt);
            }
        });

        input_telefone_cadastrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        input_telefone_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        try {
            input_telefone_cadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_telefone_cadastrar.setText("(00) 00000-0000    ");
        input_telefone_cadastrar.setToolTipText("Digite aqui seu telefone");
        input_telefone_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_telefone_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_telefone_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_telefone_cadastrarFocusLost(evt);
            }
        });

        input_data_nasc_cadastrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        input_data_nasc_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        try {
            input_data_nasc_cadastrar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_data_nasc_cadastrar.setToolTipText("Digite aqui sua data de nescimento");
        input_data_nasc_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_data_nasc_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_data_nasc_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_data_nasc_cadastrarFocusLost(evt);
            }
        });

        select_profissao_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        select_profissao_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        select_profissao_cadastrar.add("Nutricionista");
        select_profissao_cadastrar.add("Personal");

        input_cr_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_cr_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_cr_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_cr_cadastrar.setText("CR(N ou EF)");
        input_cr_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_cr_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_cr_cadastrarFocusLost(evt);
            }
        });

        input_email_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_email_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_email_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_email_cadastrar.setText("Digite aqui seu email");
        input_email_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_email_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_email_cadastrarFocusLost(evt);
            }
        });

        input_senha_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_senha_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_senha_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_senha_cadastrar.setText("Digite aqui sua senha");
        input_senha_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_senha_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_senha_cadastrarFocusLost(evt);
            }
        });

        input_confirmar_senha_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_confirmar_senha_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_confirmar_senha_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_confirmar_senha_cadastrar.setText("Confirme aqui sua senha");
        input_confirmar_senha_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_confirmar_senha_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_confirmar_senha_cadastrarFocusLost(evt);
            }
        });

        input_senha_antiga_cadastrar.setBackground(new java.awt.Color(254, 254, 254));
        input_senha_antiga_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_senha_antiga_cadastrar.setForeground(new java.awt.Color(1, 1, 1));
        input_senha_antiga_cadastrar.setText("Digite aqui sua senha antiga");
        input_senha_antiga_cadastrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_senha_antiga_cadastrarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_senha_antiga_cadastrarFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panel_cadastrarLayout = new javax.swing.GroupLayout(panel_cadastrar);
        panel_cadastrar.setLayout(panel_cadastrarLayout);
        panel_cadastrarLayout.setHorizontalGroup(
            panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cadastrarLayout.createSequentialGroup()
                .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_cadastrarLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(input_confirmar_senha_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_senha_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_email_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cadastrarLayout.createSequentialGroup()
                                .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(select_profissao_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(input_telefone_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(input_cr_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(input_data_nasc_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(input_endereco_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(input_nome_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_senha_antiga_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_cadastrarLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btn_cadastrar_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_title1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_cadastrarLayout.setVerticalGroup(
            panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cadastrarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txt_title1)
                .addGap(21, 21, 21)
                .addComponent(input_nome_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_endereco_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_data_nasc_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_telefone_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_cr_cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(select_profissao_cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_email_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(input_senha_antiga_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_senha_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_confirmar_senha_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_cadastrar_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrar_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_cadastrarActionPerformed
        // Método cadastrar que retorna um boolean
        boolean cadastrado = PersonalController.cadastro(input_nome_cadastrar.getText(), input_email_cadastrar.getText(), input_senha_cadastrar.getText(), input_confirmar_senha_cadastrar.getText(), input_data_nasc_cadastrar.getText(), input_telefone_cadastrar.getText(), input_cr_cadastrar.getText(), input_endereco_cadastrar.getText());
        //Se cadastrado com sucesso aparece a mendagem e retorna pra tela de login
        if(cadastrado){
            JOptionPane.showMessageDialog(this,"CADASTRO BEM SUCEDIDO", "Mensagem do sistema", JOptionPane.PLAIN_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"ERRO AO CADASTRAR", "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_cadastrar_cadastrarActionPerformed

    private void input_nome_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nome_cadastrarFocusGained
        input_nome_cadastrar.setText(command.executaComando(Invocador.Apagado, "Digite aqui seu nome completo", input_nome_cadastrar.getText()));
    }//GEN-LAST:event_input_nome_cadastrarFocusGained

    private void input_nome_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_nome_cadastrarFocusLost
        input_nome_cadastrar.setText(command.desfaz(input_nome_cadastrar.getText()));
    }//GEN-LAST:event_input_nome_cadastrarFocusLost

    private void input_endereco_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_endereco_cadastrarFocusGained
        input_endereco_cadastrar.setText(command.executaComando(Invocador.Apagado, "Digite aqui seu endereço", input_endereco_cadastrar.getText()));
    }//GEN-LAST:event_input_endereco_cadastrarFocusGained

    private void input_endereco_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_endereco_cadastrarFocusLost
        input_endereco_cadastrar.setText(command.desfaz(input_endereco_cadastrar.getText()));
    }//GEN-LAST:event_input_endereco_cadastrarFocusLost

    private void input_telefone_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_telefone_cadastrarFocusGained
        input_telefone_cadastrar.setText(command.executaComando(Invocador.Apagado, "(00) 00000-0000", input_telefone_cadastrar.getText()));
    }//GEN-LAST:event_input_telefone_cadastrarFocusGained

    private void input_telefone_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_telefone_cadastrarFocusLost
        input_telefone_cadastrar.setText(command.desfaz(input_telefone_cadastrar.getText()));
    }//GEN-LAST:event_input_telefone_cadastrarFocusLost

    private void input_data_nasc_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_data_nasc_cadastrarFocusGained
        input_data_nasc_cadastrar.setText(command.executaComando(Invocador.Apagado, "  /  /    ", input_data_nasc_cadastrar.getText()));
    }//GEN-LAST:event_input_data_nasc_cadastrarFocusGained

    private void input_data_nasc_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_data_nasc_cadastrarFocusLost
        input_data_nasc_cadastrar.setText(command.desfaz(input_data_nasc_cadastrar.getText()));
    }//GEN-LAST:event_input_data_nasc_cadastrarFocusLost

    private void input_cr_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cr_cadastrarFocusGained
        input_cr_cadastrar.setText(command.executaComando(Invocador.Apagado, "CR(N ou EF)", input_cr_cadastrar.getText()));
    }//GEN-LAST:event_input_cr_cadastrarFocusGained

    private void input_cr_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_cr_cadastrarFocusLost
        input_cr_cadastrar.setText(command.desfaz(input_cr_cadastrar.getText()));
    }//GEN-LAST:event_input_cr_cadastrarFocusLost

    private void input_email_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_email_cadastrarFocusGained
        input_email_cadastrar.setText(command.executaComando(Invocador.Apagado, "Digite aqui seu email", input_email_cadastrar.getText()));
    }//GEN-LAST:event_input_email_cadastrarFocusGained

    private void input_email_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_email_cadastrarFocusLost
        input_email_cadastrar.setText(command.desfaz(input_email_cadastrar.getText()));
    }//GEN-LAST:event_input_email_cadastrarFocusLost

    private void input_senha_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_senha_cadastrarFocusGained
        input_senha_cadastrar.setEchoChar('*');
        input_senha_cadastrar.setText(command.executaComando(Invocador.Apagado, "Digite aqui sua senha", input_senha_cadastrar.getText()));
    }//GEN-LAST:event_input_senha_cadastrarFocusGained

    private void input_senha_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_senha_cadastrarFocusLost
        input_senha_cadastrar.setText(command.desfaz(input_senha_cadastrar.getText()));
    }//GEN-LAST:event_input_senha_cadastrarFocusLost

    private void input_confirmar_senha_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_confirmar_senha_cadastrarFocusGained
        input_confirmar_senha_cadastrar.setEchoChar('*');
        input_confirmar_senha_cadastrar.setText(command.executaComando(Invocador.Apagado, "Confirme aqui sua senha", input_confirmar_senha_cadastrar.getText()));
    }//GEN-LAST:event_input_confirmar_senha_cadastrarFocusGained

    private void input_confirmar_senha_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_confirmar_senha_cadastrarFocusLost
        input_confirmar_senha_cadastrar.setText(command.desfaz(input_confirmar_senha_cadastrar.getText()));
    }//GEN-LAST:event_input_confirmar_senha_cadastrarFocusLost

    private void input_senha_antiga_cadastrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_senha_antiga_cadastrarFocusGained
        input_senha_antiga_cadastrar.setEchoChar('*');
        input_senha_antiga_cadastrar.setText(command.executaComando(Invocador.Apagado, "Digite aqui sua senha antiga", input_senha_antiga_cadastrar.getText()));
         // TODO add your handling code here:
    }//GEN-LAST:event_input_senha_antiga_cadastrarFocusGained

    private void input_senha_antiga_cadastrarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_senha_antiga_cadastrarFocusLost
        input_senha_antiga_cadastrar.setText(command.desfaz(input_senha_antiga_cadastrar.getText()));
       // TODO add your handling code here:
    }//GEN-LAST:event_input_senha_antiga_cadastrarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcessConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcessConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcessConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcessConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcessConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_cadastrar_cadastrar;
    private java.awt.TextField input_confirmar_senha_cadastrar;
    private java.awt.TextField input_cr_cadastrar;
    private javax.swing.JFormattedTextField input_data_nasc_cadastrar;
    private java.awt.TextField input_email_cadastrar;
    private java.awt.TextField input_endereco_cadastrar;
    private java.awt.TextField input_nome_cadastrar;
    private java.awt.TextField input_senha_antiga_cadastrar;
    private java.awt.TextField input_senha_cadastrar;
    private javax.swing.JFormattedTextField input_telefone_cadastrar;
    private javax.swing.JPanel panel_cadastrar;
    private java.awt.Choice select_profissao_cadastrar;
    private javax.swing.JLabel txt_title1;
    // End of variables declaration//GEN-END:variables

    private void preencherInformacoes(){
        input_nome_cadastrar.setText(PersonalLogado.getInstance().getUsuario().getName());
        input_email_cadastrar.setText(PersonalLogado.getInstance().getUsuario().getEmail());
        input_telefone_cadastrar.setText(PersonalLogado.getInstance().getUsuario().getTelephone());
        input_data_nasc_cadastrar.setText(PersonalLogado.getInstance().getUsuario().getTelephone());
        input_email_cadastrar.setText(PersonalLogado.getInstance().getUsuario().getEmail());
        input_endereco_cadastrar.setText(PersonalLogado.getInstance().getUsuario().getAddress());
        input_cr_cadastrar.setText(PersonalLogado.getInstance().getUsuario().getCref());
        select_profissao_cadastrar.select(1);
    }
}
