/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Insert;

import command.Invocador;
import control.AlunoController;
import control.ExercicioController;
import control.TreinoAlunoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.ExercicioList;

/**
 *
 * @author vivi
 */
public class InsertTreinoAluno extends javax.swing.JFrame {

     // Invocador do padrão command na pasta "command"
    Invocador command = Invocador.getInstace();
    private static InsertTreinoAluno treino;
    private String id_aluno;
    private String id_treino;


    /**
     * Creates new form CadastrarAlunoVisual
     */
    private InsertTreinoAluno(String id_aluno, String id_treino) {
        initComponents();
        this.id_aluno = id_aluno;
        this.id_treino = id_treino;
        
        setNomeAluno();
        setNomeSelecao();
        setSelecaoCampos();
    }
    
    private InsertTreinoAluno(){
        initComponents();
    }
    
    public static InsertTreinoAluno getInstance(String id_aluno, String id_treino) {
        if (treino == null) {
            treino = new InsertTreinoAluno(id_aluno, id_treino);
        }
        return treino;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_exercicio = new javax.swing.JPanel();
        input_email = new java.awt.TextField();
        txt_titulo = new java.awt.Label();
        btn_inserir = new java.awt.Button();
        table_principal = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        select_exercicio = new java.awt.Choice();
        txt_titulo1 = new java.awt.Label();
        input_divisao = new java.awt.TextField();
        input_series = new java.awt.TextField();
        input_metodologia = new java.awt.TextField();
        input_repeticoes = new java.awt.TextField();
        input_comentarios = new java.awt.TextArea();
        btn_att = new java.awt.Button();
        btn_add_exerc = new java.awt.Button();
        btn_excluir = new java.awt.Button();
        btn_cadastrar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 450));
        setMinimumSize(new java.awt.Dimension(550, 450));

        panel_exercicio.setBackground(new java.awt.Color(254, 254, 254));
        panel_exercicio.setMaximumSize(new java.awt.Dimension(550, 450));
        panel_exercicio.setMinimumSize(new java.awt.Dimension(550, 450));

        input_email.setBackground(new java.awt.Color(254, 254, 254));
        input_email.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_email.setText("Digite aqui o objetivo do treino");
        input_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_emailFocusLost(evt);
            }
        });

        txt_titulo.setAlignment(java.awt.Label.CENTER);
        txt_titulo.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        txt_titulo.setText("inserir Treino");

        btn_inserir.setBackground(new java.awt.Color(254, 254, 254));
        btn_inserir.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_inserir.setLabel("Inserir");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        tabela.setBackground(new java.awt.Color(254, 254, 254));
        tabela.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        tabela.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        tabela.setForeground(new java.awt.Color(1, 1, 1));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_exercicio", "exercicio", "divisao", "metodologia", "series", "repeticoes", "comentarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setRowHeight(20);
        tabela.setShowGrid(true);
        tabela.setShowVerticalLines(false);
        tabela.getColumnModel().getColumn(0).setMaxWidth(0);
        tabela.getColumnModel().getColumn(0).setMinWidth(0);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(0);
        tabela.getColumnModel().getColumn(0).setResizable(false);
        table_principal.setViewportView(tabela);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(488, 146));
        jPanel1.setMinimumSize(new java.awt.Dimension(488, 146));

        select_exercicio.setBackground(new java.awt.Color(254, 254, 254));
        select_exercicio.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N

        txt_titulo1.setAlignment(java.awt.Label.CENTER);
        txt_titulo1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        txt_titulo1.setText("Exercicio");

        input_divisao.setBackground(new java.awt.Color(254, 254, 254));
        input_divisao.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_divisao.setForeground(new java.awt.Color(1, 1, 1));
        input_divisao.setText("divisao");
        input_divisao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_divisaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_divisaoFocusLost(evt);
            }
        });

        input_series.setBackground(new java.awt.Color(254, 254, 254));
        input_series.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_series.setForeground(new java.awt.Color(1, 1, 1));
        input_series.setText("series");
        input_series.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_seriesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_seriesFocusLost(evt);
            }
        });

        input_metodologia.setBackground(new java.awt.Color(254, 254, 254));
        input_metodologia.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_metodologia.setForeground(new java.awt.Color(1, 1, 1));
        input_metodologia.setText("metodologia");
        input_metodologia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_metodologiaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_metodologiaFocusLost(evt);
            }
        });

        input_repeticoes.setBackground(new java.awt.Color(254, 254, 254));
        input_repeticoes.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_repeticoes.setForeground(new java.awt.Color(1, 1, 1));
        input_repeticoes.setText("repeticoes");
        input_repeticoes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_repeticoesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_repeticoesFocusLost(evt);
            }
        });

        input_comentarios.setBackground(new java.awt.Color(254, 254, 254));
        input_comentarios.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_comentarios.setMaximumSize(new java.awt.Dimension(100, 80));
        input_comentarios.setName(""); // NOI18N
        input_comentarios.setText("Comentarios");
        input_comentarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_comentariosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_comentariosFocusLost(evt);
            }
        });

        btn_att.setActionCommand("-");
        btn_att.setBackground(new java.awt.Color(68, 68, 68));
        btn_att.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_att.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_att.setForeground(new java.awt.Color(254, 254, 254));
        btn_att.setLabel("atualizar selecao");
        btn_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attActionPerformed(evt);
            }
        });

        btn_add_exerc.setActionCommand("-");
        btn_add_exerc.setBackground(new java.awt.Color(68, 68, 68));
        btn_add_exerc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_add_exerc.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_add_exerc.setForeground(new java.awt.Color(254, 254, 254));
        btn_add_exerc.setLabel("+");
        btn_add_exerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_exercActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_titulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(select_exercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_comentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(input_divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(input_metodologia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(input_series, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(input_repeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(btn_add_exerc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txt_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(select_exercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_att, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_add_exerc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_series, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_repeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_divisao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_metodologia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(input_comentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        btn_excluir.setActionCommand("-");
        btn_excluir.setBackground(new java.awt.Color(68, 68, 68));
        btn_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_excluir.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_excluir.setForeground(new java.awt.Color(254, 254, 254));
        btn_excluir.setLabel(" - exercicio");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cadastrar.setActionCommand("-");
        btn_cadastrar.setBackground(new java.awt.Color(68, 68, 68));
        btn_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cadastrar.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(254, 254, 254));
        btn_cadastrar.setLabel(" + exercicio");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_exercicioLayout = new javax.swing.GroupLayout(panel_exercicio);
        panel_exercicio.setLayout(panel_exercicioLayout);
        panel_exercicioLayout.setHorizontalGroup(
            panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_exercicioLayout.createSequentialGroup()
                .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(table_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_exercicioLayout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel_exercicioLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(input_email, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel_exercicioLayout.createSequentialGroup()
                                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panel_exercicioLayout.setVerticalGroup(
            panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_exercicioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(input_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(table_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_exercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_exercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_emailFocusGained
        input_email.setText(command.executaComando(Invocador.Apagado, "Digite aqui o objetivo do treino", input_email.getText()));
    }//GEN-LAST:event_input_emailFocusGained

    private void input_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_emailFocusLost
        input_email.setText(command.desfaz(input_email.getText()));
    }//GEN-LAST:event_input_emailFocusLost

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed
        
        ArrayList<ExercicioList> exercicios = new ArrayList<ExercicioList>();
        for(int i = 0; i < tabela.getRowCount(); i++){
            System.out.println(tabela.getRowCount());
            
            ExercicioList e = new ExercicioList();
            e.setDivision(tabela.getValueAt(i, 2).toString());
            e.setExercise(tabela.getValueAt(i, 0).toString());
            e.setMethodology(tabela.getValueAt(i, 3).toString());
            e.setSeries(Integer.parseInt(tabela.getValueAt(i, 4).toString()));
            e.setRepetitions(Integer.parseInt(tabela.getValueAt(i, 5).toString()));
            e.setComments(tabela.getValueAt(i, 6).toString());
            exercicios.add(e);
        }

        
        if(TreinoAlunoController.cadastrarTreinoAluno(id_aluno, input_email.getText(), exercicios)){
            JOptionPane.showMessageDialog(this,"CADASTRO BEM SUCEDIDO", "Mensagem do sistema", JOptionPane.PLAIN_MESSAGE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"ERRO AO CADASTRAR", "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btn_inserirActionPerformed

    private void input_metodologiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_metodologiaFocusGained
        input_metodologia.setText(command.executaComando(Invocador.Apagado, "metodologia", input_metodologia.getText()));
    }//GEN-LAST:event_input_metodologiaFocusGained

    private void input_metodologiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_metodologiaFocusLost
        input_metodologia.setText(command.desfaz(input_metodologia.getText()));
    }//GEN-LAST:event_input_metodologiaFocusLost

    private void input_seriesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_seriesFocusGained
        input_series.setText(command.executaComando(Invocador.Apagado, "series", input_series.getText()));
    }//GEN-LAST:event_input_seriesFocusGained

    private void input_seriesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_seriesFocusLost
        input_series.setText(command.desfaz(input_series.getText()));
    }//GEN-LAST:event_input_seriesFocusLost

    private void input_repeticoesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_repeticoesFocusGained
        input_repeticoes.setText(command.executaComando(Invocador.Apagado, "repeticoes", input_repeticoes.getText()));
    }//GEN-LAST:event_input_repeticoesFocusGained

    private void input_repeticoesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_repeticoesFocusLost
        input_repeticoes.setText(command.desfaz(input_repeticoes.getText()));
    }//GEN-LAST:event_input_repeticoesFocusLost

    private void input_divisaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_divisaoFocusGained
        input_divisao.setText(command.executaComando(Invocador.Apagado, "divisao", input_divisao.getText()));
    }//GEN-LAST:event_input_divisaoFocusGained

    private void input_divisaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_divisaoFocusLost
        input_divisao.setText(command.desfaz(input_divisao.getText()));
    }//GEN-LAST:event_input_divisaoFocusLost

    private void input_comentariosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_comentariosFocusLost
        input_comentarios.setText(command.executaComando(Invocador.Apagado, "comentarios", input_comentarios.getText()));
    }//GEN-LAST:event_input_comentariosFocusLost

    private void input_comentariosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_comentariosFocusGained
        input_comentarios.setText(command.desfaz(input_comentarios.getText()));
    }//GEN-LAST:event_input_comentariosFocusGained

    private void btn_add_exercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_exercActionPerformed
        InserExercicio.getInstance().setVisible(true);
    }//GEN-LAST:event_btn_add_exercActionPerformed

    private void btn_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attActionPerformed
        setSelecaoCampos();
    }//GEN-LAST:event_btn_attActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
         // Constroi um parâmetro de tabela que começa com 0 linha, 0 coluna
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        
        String [] id_exercio = getIdExercicio();
        
        model.addRow(new Object[]{id_exercio[select_exercicio.getSelectedIndex()], select_exercicio.getSelectedItem(), input_divisao.getText(), input_metodologia.getText(), input_series.getText(), input_repeticoes.getText(), input_comentarios.getText()});
                
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int linha = tabela.getSelectedRow();
        if(linha >= 0){
            DefaultTableModel model = (DefaultTableModel)tabela.getModel();
            model.removeRow(linha);
            
        }else{
            JOptionPane.showMessageDialog(this,"SELECIONE UM EXERCICIO", "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertTreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertTreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertTreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertTreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertTreinoAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_add_exerc;
    private java.awt.Button btn_att;
    private java.awt.Button btn_cadastrar;
    private java.awt.Button btn_excluir;
    private java.awt.Button btn_inserir;
    private java.awt.TextArea input_comentarios;
    private java.awt.TextField input_divisao;
    private java.awt.TextField input_email;
    private java.awt.TextField input_metodologia;
    private java.awt.TextField input_repeticoes;
    private java.awt.TextField input_series;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_exercicio;
    private java.awt.Choice select_exercicio;
    private javax.swing.JTable tabela;
    private javax.swing.JScrollPane table_principal;
    private java.awt.Label txt_titulo;
    private java.awt.Label txt_titulo1;
    // End of variables declaration//GEN-END:variables
    
    private void setNomeAluno(){
        String nome_aluno = AlunoController.getNomeAlunoByID(id_aluno);
        txt_titulo.setText("Inserir Treino de"+nome_aluno);
    }
    private void setNomeSelecao(){
        ArrayList<String> exercicio = ExercicioController.listaExercicios();
        if(!exercicio.isEmpty()){
            for(int i = 0; i < exercicio.size(); i++){
                String nome_exercicio = ExercicioController.getNomeAlunoByID(exercicio.get(i).split("/")[0]);
            }
        }
    }
    private void setSelecaoCampos(){
        select_exercicio.removeAll();

        ArrayList<String> exercio = ExercicioController.listaExercicios();
        String [] id = new String[exercio.size()];
        
        for(int i = 0; i < exercio.size(); i++){
            id[i] =  exercio.get(i).toString().split("/")[0];
            String nome = exercio.get(i).toString().split("/")[1];
            select_exercicio.add(nome);
        }
    }
    
    private String[] getIdExercicio(){
        ArrayList<String> exercio = ExercicioController.listaExercicios();
        String [] id = new String[exercio.size()];
        
        for(int i = 0; i < exercio.size(); i++){
            id[i] =  exercio.get(i).toString().split("/")[0];
            String nome = exercio.get(i).toString().split("/")[1];
        }
        return id;
    }
    
    
}
