/*
 * Tela de cadastro de exercício
 */
package view.Insert;
// Usar singleton

import command.Invocador;
import control.ExercicioController;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitória Moreira de Souza
 */
public class InserExercicio extends javax.swing.JFrame {

    // Invocador do padrão command na pasta "command"
    Invocador command = Invocador.getInstace();
    private static InserExercicio inserirExercicio;
    
    /**
     * Creates new form Aluno
     */
    private InserExercicio() {
        initComponents();
    }
    
    public static InserExercicio getInstance() {
        if (inserirExercicio == null) {
            inserirExercicio = new InserExercicio();
        }
        return inserirExercicio;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_exercicio = new javax.swing.JPanel();
        input_exercicio = new java.awt.TextField();
        input_grupo = new java.awt.TextField();
        txt_titulo = new java.awt.Label();
        btn_inserir = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 215));
        setResizable(false);

        panel_exercicio.setBackground(new java.awt.Color(254, 254, 254));
        panel_exercicio.setMinimumSize(new java.awt.Dimension(500, 215));
        panel_exercicio.setPreferredSize(new java.awt.Dimension(500, 215));

        input_exercicio.setBackground(new java.awt.Color(254, 254, 254));
        input_exercicio.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_exercicio.setText("Digite aqui o nome do exercicio");
        input_exercicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_exercicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_exercicioFocusLost(evt);
            }
        });

        input_grupo.setBackground(new java.awt.Color(254, 254, 254));
        input_grupo.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_grupo.setText("Digite aqui o grupo do exercicio");
        input_grupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_grupoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_grupoFocusLost(evt);
            }
        });

        txt_titulo.setAlignment(java.awt.Label.CENTER);
        txt_titulo.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        txt_titulo.setText("Inserir Exercicio");

        btn_inserir.setBackground(new java.awt.Color(254, 254, 254));
        btn_inserir.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_inserir.setLabel("Inserir");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_exercicioLayout = new javax.swing.GroupLayout(panel_exercicio);
        panel_exercicio.setLayout(panel_exercicioLayout);
        panel_exercicioLayout.setHorizontalGroup(
            panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exercicioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exercicioLayout.createSequentialGroup()
                        .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(input_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_exercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
            .addGroup(panel_exercicioLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_exercicioLayout.setVerticalGroup(
            panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_exercicioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(input_exercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(input_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_exercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_exercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed
        if(ExercicioController.inserirExercicio(input_exercicio.getText(), input_grupo.getText())){
            JOptionPane.showMessageDialog(this,"CADASTRO BEM SUCEDIDO", "Mensagem do sistema", JOptionPane.PLAIN_MESSAGE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"ERRO AO CADASTRAR", "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_inserirActionPerformed

    private void input_exercicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_exercicioFocusGained
        input_exercicio.setText(command.executaComando(Invocador.Apagado, "Digite aqui o nome do exercicio", input_exercicio.getText()));
    }//GEN-LAST:event_input_exercicioFocusGained

    private void input_exercicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_exercicioFocusLost
        input_exercicio.setText(command.desfaz(input_exercicio.getText()));
    }//GEN-LAST:event_input_exercicioFocusLost

    private void input_grupoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_grupoFocusGained
        input_grupo.setText(command.executaComando(Invocador.Apagado, "Digite aqui o grupo do exercicio", input_grupo.getText()));
    }//GEN-LAST:event_input_grupoFocusGained

    private void input_grupoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_grupoFocusLost
        input_grupo.setText(command.desfaz(input_grupo.getText()));
    }//GEN-LAST:event_input_grupoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserExercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_inserir;
    private java.awt.TextField input_exercicio;
    private java.awt.TextField input_grupo;
    private javax.swing.JPanel panel_exercicio;
    private java.awt.Label txt_titulo;
    // End of variables declaration//GEN-END:variables

}
