/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Insert;

import command.Invocador;
import control.AlunoController;
import javax.swing.JOptionPane;

/**
 *
 * @author vivi
 */
public class IsertAluno extends javax.swing.JFrame {

     // Invocador do padrão command na pasta "command"
    Invocador command = Invocador.getInstace();
    private static IsertAluno aluno;

    /**
     * Creates new form CadastrarAlunoVisual
     */
    public IsertAluno() {
        initComponents();
    }
    
    
    
    public static IsertAluno getInstance() {
        if (aluno == null) {
            aluno = new IsertAluno();
        }
        return aluno;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_exercicio = new javax.swing.JPanel();
        input_aluno = new java.awt.TextField();
        input_email = new java.awt.TextField();
        txt_titulo = new java.awt.Label();
        btn_inserir = new java.awt.Button();
        input_data_nasc = new javax.swing.JFormattedTextField();
        input_senha = new java.awt.TextField();
        input_confirmar_senha = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_exercicio.setBackground(new java.awt.Color(254, 254, 254));
        panel_exercicio.setMaximumSize(new java.awt.Dimension(500, 300));
        panel_exercicio.setMinimumSize(new java.awt.Dimension(500, 300));

        input_aluno.setBackground(new java.awt.Color(254, 254, 254));
        input_aluno.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_aluno.setText("Digite aqui o nome do aluno");
        input_aluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_alunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_alunoFocusLost(evt);
            }
        });

        input_email.setBackground(new java.awt.Color(254, 254, 254));
        input_email.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_email.setText("Digite aqui o email do aluno");
        input_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_emailFocusLost(evt);
            }
        });

        txt_titulo.setAlignment(java.awt.Label.CENTER);
        txt_titulo.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        txt_titulo.setText("Inserir Aluno");

        btn_inserir.setBackground(new java.awt.Color(254, 254, 254));
        btn_inserir.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        btn_inserir.setLabel("Inserir");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        input_data_nasc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        input_data_nasc.setForeground(new java.awt.Color(1, 1, 1));
        try {
            input_data_nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_data_nasc.setToolTipText("Digite aqui a data de nescimento do aluno");
        input_data_nasc.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_data_nasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_data_nascFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_data_nascFocusLost(evt);
            }
        });

        input_senha.setBackground(new java.awt.Color(254, 254, 254));
        input_senha.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_senha.setForeground(new java.awt.Color(1, 1, 1));
        input_senha.setText("Digite aqui a senha do aluno");
        input_senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_senhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_senhaFocusLost(evt);
            }
        });

        input_confirmar_senha.setBackground(new java.awt.Color(254, 254, 254));
        input_confirmar_senha.setFont(new java.awt.Font("Courier 10 Pitch", 0, 14)); // NOI18N
        input_confirmar_senha.setForeground(new java.awt.Color(1, 1, 1));
        input_confirmar_senha.setText("Confirme aqui a senha do aluno");
        input_confirmar_senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                input_confirmar_senhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                input_confirmar_senhaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panel_exercicioLayout = new javax.swing.GroupLayout(panel_exercicio);
        panel_exercicio.setLayout(panel_exercicioLayout);
        panel_exercicioLayout.setHorizontalGroup(
            panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exercicioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exercicioLayout.createSequentialGroup()
                        .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_confirmar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(input_email, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                                .addComponent(input_aluno, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                                .addComponent(input_data_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(input_senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(44, 44, 44))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exercicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        panel_exercicioLayout.setVerticalGroup(
            panel_exercicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_exercicioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(input_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_confirmar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_data_nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_exercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_exercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void input_alunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_alunoFocusGained
        input_aluno.setText(command.executaComando(Invocador.Apagado, "Digite aqui o nome do aluno", input_aluno.getText()));
    }//GEN-LAST:event_input_alunoFocusGained

    private void input_alunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_alunoFocusLost
        input_aluno.setText(command.desfaz(input_aluno.getText()));
    }//GEN-LAST:event_input_alunoFocusLost

    private void input_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_emailFocusGained
        input_email.setText(command.executaComando(Invocador.Apagado, "Digite aqui o email do aluno", input_email.getText()));
    }//GEN-LAST:event_input_emailFocusGained

    private void input_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_emailFocusLost
        input_email.setText(command.desfaz(input_email.getText()));
    }//GEN-LAST:event_input_emailFocusLost

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed
        if(AlunoController.inserirAlunoUsuario(input_aluno.getText(), input_email.getText(), input_senha.getText(), input_confirmar_senha.getText(), input_data_nasc.getText())){
            JOptionPane.showMessageDialog(this,"CADASTRO BEM SUCEDIDO", "Mensagem do sistema", JOptionPane.PLAIN_MESSAGE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"ERRO AO CADASTRAR", "Mensagem do sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_inserirActionPerformed

    private void input_data_nascFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_data_nascFocusGained
        input_data_nasc.setText(command.executaComando(Invocador.Apagado, "  /  /    ", input_data_nasc.getText()));
    }//GEN-LAST:event_input_data_nascFocusGained

    private void input_data_nascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_data_nascFocusLost
        input_data_nasc.setText(command.desfaz(input_data_nasc.getText()));
    }//GEN-LAST:event_input_data_nascFocusLost

    private void input_senhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_senhaFocusGained
        input_senha.setEchoChar('*');
        input_senha.setText(command.executaComando(Invocador.Apagado, "Digite aqui a senha do aluno", input_senha.getText()));
    }//GEN-LAST:event_input_senhaFocusGained

    private void input_senhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_senhaFocusLost
        input_senha.setText(command.desfaz(input_senha.getText()));
    }//GEN-LAST:event_input_senhaFocusLost

    private void input_confirmar_senhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_confirmar_senhaFocusGained
        input_confirmar_senha.setEchoChar('*');
        input_confirmar_senha.setText(command.executaComando(Invocador.Apagado, "Confirme aqui a senha do aluno", input_confirmar_senha.getText()));
    }//GEN-LAST:event_input_confirmar_senhaFocusGained

    private void input_confirmar_senhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_input_confirmar_senhaFocusLost
        input_confirmar_senha.setText(command.desfaz(input_confirmar_senha.getText()));
    }//GEN-LAST:event_input_confirmar_senhaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IsertAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IsertAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IsertAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IsertAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IsertAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_inserir;
    private java.awt.TextField input_aluno;
    private java.awt.TextField input_confirmar_senha;
    private javax.swing.JFormattedTextField input_data_nasc;
    private java.awt.TextField input_email;
    private java.awt.TextField input_senha;
    private javax.swing.JPanel panel_exercicio;
    private java.awt.Label txt_titulo;
    // End of variables declaration//GEN-END:variables
 
}
